/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mailbox.h"

bool_t
xdr_message_params (XDR *xdrs, message_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->message_num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 80))
		 return FALSE;
	return TRUE;
}
